name = "basic"
license = "MIT"
description = "Basic theme, adapted from hugo-xmin"
tags = ["tags", "categories", "blog"]
features = ["blog"]
min_version = "0.33"

[original]
  author = "Yihui Xui"
  homepage = "https://xmin.yihui.name/"
  repo = "https://github.com/yihui/hugo-xmin"
